### ISSUE TITLE
All Labs Link redirects to inappropriate page

### ISSUE THREAD

**Issue by BSravanthi** [integration-team-iiith/molecular-absorption-spectroscopy-responsive-lab#8]
In the Molecular Absorption Spectroscopy lab, in the main page of this lab and all the 7 links of the home page, The "All Labs" link in the header section is redirecting to the Vlabs main/Home page. Where as the link should direct to the page which shows the Discipline wise lab's list.

**Comment by sadhanareddy** [comment]
Issue is resolved now.  Corrected the "AllLabs" link in all the 7 links of the home page.

**Comment by BSravanthi** [comment]
The All Labs link in all the seven pages of main page are updated, but in the Home page the link is not updated. Hence reopening the issue.

**Comment by sadhanareddy** [comment]
Link is updated. Issue is fixed now.

**Comment by BSravanthi** [comment]
In the landing page still the "All Lab" link is redirecting to the vlabs landing page. In rest of the pages the issue is fixed. Re opening the issue as the issue is still persists on Landing page.

**Comment by sadhanareddy** [comment]
Issue is fixed now. Link is redirecting to the appropriate page.

**Comment by sadhanareddy** [comment]
After a discussion with Lalit, came to a conclusion that, these issues need not to be fixed as the content of the lab will be ported to open edx.
While redirection of the links of the lab to openedx, they were broken. Hence differing this issue.
